// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.layout.display-list.retain", true);
user_pref("app.normandy.startupRolloutPrefs.security.tls.version.fallback-limit", 4);
user_pref("app.normandy.user_id", "9b1c5f9e-2c18-47c3-a02d-1e2b7d2964cf");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1538465870);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1538465990);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1538465509);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1538465750);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1538465629);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1538466230);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1538466110);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1538465480);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{cd779950-678c-444b-b58b-18ce72d98be8}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1538463600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1538465485);
user_pref("browser.onboarding.notification.prompt-count", 2);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1538468347387");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1538470143387");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1538465496305");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1538469096305");
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180704192850");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1538468415");
user_pref("browser.slowStartup.averageTime", 5396);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180704192850");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1538465490101");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Tue, 18 Sep 2018 22:29:12 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1538465871);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180704192850");
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"1927a5a7-58c9-4b95-899c-9537c30516cc\",\"screenshots@mozilla.org\":\"2b33e8ab-ff4e-48ac-9e64-405cc57b8974\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("idle.lastDailyNotification", 1538465817);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1538465606);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180704192850");
user_pref("media.gmp-manager.lastCheck", 1538465604);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1538465817);
user_pref("places.history.expiration.transient_current_max_pages", 57643);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c7eeea1d-cecc-4f00-8028-466e931eec61");
user_pref("services.blocklist.addons.checked", 1538422915);
user_pref("services.blocklist.gfx.checked", 1538422915);
user_pref("services.blocklist.onecrl.checked", 1538422915);
user_pref("services.blocklist.pinning.checked", 1538422915);
user_pref("services.blocklist.plugins.checked", 1538422915);
user_pref("services.settings.clock_skew_seconds", 43075);
user_pref("services.settings.last_etag", "\"1538203644395\"");
user_pref("services.settings.last_update_seconds", 1538422915);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1538465817);
user_pref("toolkit.startup.last_success", 1538468410);
user_pref("toolkit.telemetry.cachedClientID", "6e19989d-f46d-4a39-8fda-3dc1d942556d");
user_pref("toolkit.telemetry.previousBuildID", "20180704192850");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
